[workspace]

members = [
  "crates/pichpich",
  "crates/pichpich_config",
  "crates/internal_tools",
]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[profile.dev.package.pichpich]
overflow-checks = true
